### ISSUE TITLE
Memory leak in api or core

### ISSUE THREAD

**Issue by pajtai** [Solid-Interactive/grasshopper-api-js#8]
STR:
go to a node with content
refresh the page multiple times

node process memory increases (use pm2 list or just htop to see)

**Comment by travism** [comment]
For "go to a node with content" are you talking about the using grasshopper admin with a lot of content in a node?

**Comment by pajtai** [comment]
with just one - but after playing around with this, I'm not convinced it's grasshopper ----- using grasshopper fly, I was not able to repro.... will close this until I get more details
