### ISSUE TITLE
Tests are failing but appear to be passing on Travis

### ISSUE THREAD

**Issue by pajtai** [Solid-Interactive/grasshopper-api-js#9]
Tests should be updated in the same way as was done for gh-core

**Comment by travism** [comment]
My tests are working locally for multiple versions of node both locally and on travis. Going to close this one.

**Comment by pajtai** [comment]
@travism what command do you use to run the tests?

with `npm test` / `grunt test`, I have 123 failures. What do you do besides `npm install; npm test`. 

I would love to get to the bottom of this, since I know it fails on Cooper's, and Greg's computers too.

Node: `5.0.0`
Mongo: `3.2.4`

**Comment by travism** [comment]
Did you retry it? I don't have any issues at all 123 passing. I made some mongo dependency changes. Hopefully you retried it before reopening.

**Comment by pajtai** [comment]
Yeah, tried it yesterday on master after pulling in some changes. Did a git pull today but was all up to date.

To make sure it's not a dependency thing, I tried it again just now w an `rm -r node_modules` followed by an `npm test` and below is the full output - which is different from previously:

```
--- git/grasshopper-api-js ‹master› » npm test

> grasshopper-api@0.18.14 test /Users/pajtai/git/grasshopper-api-js
> grunt test

Failed to load c++ bson extension, using pure JS version
Running "jshint:files" (jshint) task
>> 41 files lint free.

Running "shell:testSetup" (shell) task
Failed to load c++ bson extension, using pure JS version
Running "mongodb:test" (mongodb) task
Cleaning up test database, starting from clean slate.
0 documents removed from nodes collection.
0 documents removed from contenttypes collection.
0 documents removed from users collection.
0 documents removed from content collection.
0 documents removed from tokens collection.
Collections clean.
Test `users` imported.
Test `contentTypes` imported.
Test `nodes` imported.
Test `content` imported.
Test `hookevents` imported.

Done, without errors.

Running "shell:testRun" (shell) task
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Configuration found in the environment. Using config set in process.env


  api.content
Failed to load c++ bson extension, using pure JS version
Sun, 24 Apr 2016 14:17:41 GMT express-session deprecated undefined resave option; provide resave option at lib/grasshopper-api.js:105:21
Sun, 24 Apr 2016 14:17:41 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at lib/grasshopper-api.js:105:21
Listening on port 3000...
    1) "before all" hook

  0 passing (2s)
  1 failing

  1) api.content "before all" hook:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/pajtai/git/grasshopper-api-js/node_modules/mocha/lib/runnable.js:165:14)
      at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by pajtai** [comment]
Another issue is that Travis-CI is not picking up the right exit code:

Take a look at the screenshot from this recent "passing" test:

https://travis-ci.org/Solid-Interactive/grasshopper-api-js/jobs/125277166

![travis-pass-test-fail](https://cloud.githubusercontent.com/assets/1643937/14768197/25820d14-09f0-11e6-9654-4cecb3b10697.png)

**Comment by pajtai** [comment]
Looks like `grunt-shell` has a default `failOnError` of false, just had to set it to `true` to make failing tests visible on Travis-CI.
